name: Node.js CI to ECR

on:
  push:
    branches: [ develop, main ]

env:
  AWS_REGION: eu-central-1
  CONFIG_REPO_NAME: bezeq-infra-config 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Code
        uses: actions/checkout@v3

      # 1. התקנה ובדיקות
      - name: Install dependencies
        run: npm install 

      - name: Run Tests
        run: npm test 

      # 2. התחברות ל-AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      # 3. בנייה ודחיפה של ה-Image [cite: 30]
      - name: Build and Push Image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.ref == 'refs/heads/main' && 'bezeq-app-prod-api' || (github.ref == 'refs/heads/staging' && 'bezeq-app-staging-api' || 'bezeq-app-dev-api') }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # 4. עדכון ה-Config Repo (החלק של ה-GitOps) 
      - name: Update Config Repo
        env:
          IMAGE_TAG: ${{ github.sha }}
          TARGET_BRANCH: ${{ github.ref_name }}
        run: |
          git config --global user.email "devops@bezeq.co.il"
          git config --global user.name "CI-Bot"
          
          git clone-b $TARGET_BRANCH https://${{ secrets.GH_PAT }}@github.com/${{ github.repository_owner }}/${{ env.CONFIG_REPO_NAME }}.git
          cd ${{ env.CONFIG_REPO_NAME }}
          
          ENV_DIR=$TARGET_BRANCH
        
          if [ "$TARGET_BRANCH" == "main" ]; then
            ENV_DIR="prod"
          elif [ "$TARGET_BRANCH" == "staging" ]; then
            ENV_DIR="staging"
          else
            ENV_DIR="dev"
          fi
          sed -i "s/tag:.*/tag: \"$IMAGE_TAG\"/" envs/$ENV_DIR/values.yaml
          git add envs/$ENV_DIR/values.yaml
          git commit -m "Update $ENV_DIR image tag to $IMAGE_TAG [skip ci]"
          git push origin $TARGET_BRANCH